name: Backend CI/CD (Docker build on EC2)

on:
  push:
    branches: ["fix/path"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Spring Boot App
      run: ./backend/gradlew -p backend build -x test -x spotlessJavaCheck

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY_B64 }}" | base64 -d > key.pem
        chmod 400 key.pem

    - name: Copy all deployment files to EC2
      run: |
        # 복사할 모든 파일은 backend 경로 기준
        scp -i key.pem -o StrictHostKeyChecking=no \
          backend/build/libs/*.jar \
          backend/docker-compose.yml \
          backend/Dockerfile \
          backend/.env \
          backend/src/main/resources/application.yml \
          ubuntu@43.202.247.79:/home/ubuntu/backend/

    - name: Deploy via SSH
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@43.202.247.79 << 'EOF'
          cd /home/ubuntu/backend

          echo "[1] 기존 컨테이너 중지 및 삭제"
          docker-compose down || true

          echo "[2] 최신 이미지 기반 재빌드 및 실행"
          docker-compose up -d --build
        EOF
