name: Backend CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Spring Boot App
      run: ./gradlew build -x test

    - name: Setup SSH Key (base64 decode)
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY_B64 }}" | base64 -d > key.pem
        chmod 400 key.pem

    - name: SCP JAR and application.yml to EC2
      run: |
        # EC2에 backend 디렉토리 없으면 생성
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@3.36.226.164 "mkdir -p /home/ubuntu/backend"

        # JAR 복사 후 이름 고정
        scp -i key.pem -o StrictHostKeyChecking=no build/libs/*.jar ubuntu@3.36.226.164:/home/ubuntu/backend/
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@3.36.226.164 "mv /home/ubuntu/backend/*.jar /home/ubuntu/backend/app.jar"

        # application.yml 복사
        scp -i key.pem -o StrictHostKeyChecking=no src/main/resources/application.yml ubuntu@3.36.226.164:/home/ubuntu/backend/

    - name: SSH & Restart Spring Boot
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@3.36.226.164 << 'EOF'
        cd /home/ubuntu/backend

        # 기존 실행 프로세스 찾아서 종료 (sudo 안 씀, 권한 에러 방지)
        PID=$(ps -ef | grep 'java -jar app.jar' | grep -v grep | awk '{print $2}')
        if [ -n "$PID" ]; then
          kill "$PID"
          sleep 2
        fi

        # 백그라운드로 재실행
        nohup java -jar app.jar \
        --server.port=8080 \
        --spring.config.location=file:/home/ubuntu/backend/application.yml \
        > app.log 2>&1 &
        EOF
