name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: Build Backend
        run: |
          cd backend
          ./gradlew clean build

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: backend/build/libs/*.jar
          target: /home/ubuntu/deploy-temp/backend

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            JAR_FILE=$(ls /home/ubuntu/deploy-temp/backend/*.jar | tail -n 1)
            mv "$JAR_FILE" /home/ubuntu/backend/app.jar
            sudo systemctl restart backend
