name: CI/CD Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Project (Skip tests)
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: ./gradlew test

      - name: Build Bootable Jar
        run: ./gradlew bootJar

      # ✅ Sentry 릴리스 업로드
      - name: Upload release to Sentry
        run: ./gradlew :sentryUploadRelease

      - name: Upload Artifact (Jar)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./artifact

      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Stopping existing service..."
            sudo systemctl stop cono.service
            echo "Deploying new jar file..."
            cp ./artifact/*.jar /home/ubuntu/backend/build/libs/
            echo "Starting service..."
            sudo systemctl start cono.service
            echo "Deployment completed successfully."
